### ISSUE TITLE
Guidance on VM template to use on vsphere and any pre-prep needed

### ISSUE THREAD

**Issue by Analect** [janvht/rancher-templates#1]
@janvht ... I hope you don't mind me asking a quick question here.  I had been searching for other projects experimenting with deploying an RKE2 cluster to vsphere.  Is this repo functioning in its current state?  For the VM template, I [see](https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/) you are using a RHEL box.  Is there any special pre-config required for first generating this as a RHEL template ... such as [pre-installing](https://docs.rke2.io/install/methods/) an RPM repository?  It seems your [values.yml](https://github.com/janvht/rancher-templates/blob/main/charts/rke2-on-vsphere/values.yaml) requires some hard-coded values that are not necessarily covered by the [questions.yaml](https://github.com/janvht/rancher-templates/blob/main/charts/rke2-on-vsphere/questions.yaml).  Thanks for any pointers you might have.

**Comment by janvht** [comment]
Hi Analect,

No problem at all. It is indeed functioning. The purpose was to make cluster deployments easier by using some pre-configured variables that can be put into the values file. I see your point of wanting those variables in the questions file as well.
I tested it using a RHEL template VM. Nothing too special though:
- Ip forwarding enabled in sysctl.conf
- separate vmdk mounted to /var/lib/rancher
- extra packages installed:
  - cloud-init
  - in case you want have selinux enabled – which is a best practice:
    - container-selinux
    - selinux-policy-base
  - in case you want to use ipvs (f.e. kube-proxy in ipvs mode or kube-vip for load balanced services):
    - ipset
    - ipvsadm
- before converting the VM to a template, I executed these commands:
  - echo > /etc/resolv.conf
  - echo > /etc/hosts
  - echo > /etc/hostname
  - echo > /etc/machine-id
  - cloud-init clean -s -l
  - history -c
  - shutdown -h now

If you adjust something to the template afterwards, make sure you execute the mentioned commands again as Rancher uses cloud-init to configure the machine (most cloud-init parameters are implicitly added by rancher; so they can’t be found in the rke2 template).
I guess this should work with a template of any distro as long as cloud-init is installed.

Kind regards,
Jan

**Comment by Analect** [comment]
Thanks Jan. That's very helpful.  I was just wondering about the part:
> separate vmdk mounted to /var/lib/rancher

What should get mounted there?  Could you point me to any documentation anywhere ref. this part? Best. Colum

**Comment by janvht** [comment]
Hi, it is just way too have the rke2 data (manifests, images, volumes, etc) on a separate disk for system management reasons.

**Comment by Analect** [comment]
Thanks again @janvht

**Comment by janvht** [comment]
Hi Analect,

No problem at all. It is indeed functioning. The purpose was to make cluster deployments easier by using some pre-configured variables that can be put into the values file. I see your point of wanting those variables in the questions file as well.
I tested it using a RHEL template VM. Nothing too special though:

 *   Ip forwarding enabled in sysctl.conf
 *   separate vmdk mounted to /var/lib/rancher
 *   extra packages installed:
    *   cloud-init
    *   in case you want have selinux enabled – which is a best practice:
       *   container-selinux
       *   selinux-policy-base
    *   in case you want to use ipvs (f.e. kube-proxy in ipvs mode or kube-vip for load balanced services):
       *   ipset
       *   ipvsadm
 *   before converting the VM to a template, I executed these commands:
    *   echo > /etc/resolv.conf
    *   echo > /etc/hosts
    *   echo > /etc/hostname
    *   echo > /etc/machine-id
    *   cloud-init clean -s -l
    *   history -c
    *   shutdown -h now

If you adjust something to the template afterwards, make sure you execute the mentioned commands again as Rancher uses cloud-init to configure the machine (most cloud-init parameters are implicitly added by rancher; so they can’t be found in the rke2 template).
I guess this should work with a template of any distro as long as cloud-init is installed.

Kind regards,
Jan


Jan Verhaert
ICT system engineer - Teamleader ICT Architecture & Platforms
+32 16 39 04 57
***@***.******@***.***>
Groep IDEWE | Interleuvenlaan 58 | 3001 Heverlee


<https://www.idewe.be/>[cid:goedevoornemens000_c4eff03c-9041-4dd5-aaeb-29e23c34988f_9c499ef8-7d75-4beb-8435-1b8c9a2b45ca.jpg]<https://www.idewe.be/><https://www.idewe.be/><https://www.idewe.be/><https://www.idewe.be/><http://www.idewe.be/> <http://www.idewe.be/wps/PA_Internet_site/resources/document/f12ca58b-1108-4c60-a37b-2d6429c3daf8/IDEWE_Opleidingskalender_2017nj_NL_LR.pdf> <https://www.idewe.be/coronavaccinatie-faq> [cid:mvo-rapport001_2a8e6831-ec74-4089-b2e9-4d7038d6ea11.jpg] [cid:mvo-rapport002_f7127adb-eec4-4529-a981-beb6a699a2aa.jpg] <https://www.idewe.be/-/mvo-rapport-2020-2021> [cid:mvo-rapport003_7398f83a-95bc-44b8-b70e-4ce603b6c587.jpg] <https://www.idewe.be/-/mvo-rapport-2020-2021> <https://www.idewe.be/panel-de-recherche>
<http://www.idewe.be/wps/PA_Internet_site/resources/document/e4b56f0c-b32d-4224-992b-573f88fb1bd3/IDEWE_Opleidingskalender_2017nj_FR_LR.pdf>
     (e-mail disclaimer NL <https://www.idewe.be/disclaimer>  / FR <https://www.idewe.be/fr/disclaimer>  )


Van: Analect ***@***.***>
Verzonden: maandag 20 juni 2022 16:34
Aan: janvht/rancher-templates ***@***.***>
CC: Jan Verhaert ***@***.***>; Mention ***@***.***>
Onderwerp: [janvht/rancher-templates] Guidance on VM template to use on vsphere and any pre-prep needed (Issue #1)


@janvht<https://github.com/janvht> ... I hope you don't mind me asking a quick question here. I had been searching for other projects experimenting with deploying an RKE2 cluster to vsphere. Is this repo functioning in its current state? For the VM template, I see<https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/creating-a-vm-template/> you are using a RHEL box. Is there any special pre-config required for first generating this as a RHEL template ... such as pre-installing<https://docs.rke2.io/install/methods/> an RPM repository? It seems your values.yml<https://github.com/janvht/rancher-templates/blob/main/charts/rke2-on-vsphere/values.yaml> requires some hard-coded values that are not necessarily covered by the questions.yaml<https://github.com/janvht/rancher-templates/blob/main/charts/rke2-on-vsphere/questions.yaml>. Thanks for any pointers you might have.
